version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: cronuser
      POSTGRES_PASSWORD: cronpass
      POSTGRES_DB: cronmaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
